# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sound_light.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'sound_light.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11sound_light.proto\"R\n\x07Message\x12\x19\n\x07request\x18\x01 \x01(\x0b\x32\x08.Request\x12\x1b\n\x08response\x18\x02 \x01(\x0b\x32\t.Response\x12\x0f\n\x07\x62\x61\x63kend\x18\x03 \x01(\x0c\"\x82\x01\n\x07Request\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\tsessionId\x18\xc8\x01 \x01(\t\x12!\n\x0bgetSettings\x18\x05 \x01(\x0b\x32\x0c.GetSettings\x12\x1b\n\x08settings\x18\x06 \x01(\x0b\x32\t.Settings\x12\x17\n\x06status\x18\n \x01(\x0b\x32\x07.Status\"~\n\x08Response\x12\x11\n\trequestId\x18\x01 \x01(\x05\x12\x12\n\nstatusCode\x18\x02 \x01(\x05\x12\x15\n\rstatusMessage\x18\x03 \x01(\t\x12\x1b\n\x08settings\x18\x04 \x01(\x0b\x32\t.Settings\x12\x17\n\x06status\x18\x06 \x01(\x0b\x32\x07.Status\"V\n\x0bGetSettings\x12\x0b\n\x03\x61ll\x18\x01 \x01(\x08\x12\x13\n\x0bsavedSounds\x18\x07 \x01(\x08\x12\x13\n\x0btemperature\x18\x08 \x01(\x08\x12\x10\n\x08humidity\x18\t \x01(\x08\"\xb0\x01\n\x08Settings\x12\x12\n\nbrightness\x18\x01 \x01(\x02\x12\x15\n\x05\x63olor\x18\x02 \x01(\x0b\x32\x06.Color\x12\x0e\n\x06volume\x18\x03 \x01(\x02\x12\x15\n\x05sound\x18\x04 \x01(\x0b\x32\x06.Sound\x12\x0c\n\x04isOn\x18\x05 \x01(\x08\x12\x1d\n\tsoundList\x18\x06 \x01(\x0b\x32\n.SoundList\x12\x13\n\x0btemperature\x18\x07 \x01(\x02\x12\x10\n\x08humidity\x18\x08 \x01(\x02\"9\n\x05\x43olor\x12\x0f\n\x07noColor\x18\x01 \x01(\x08\x12\x0b\n\x03hue\x18\x02 \x01(\x02\x12\x12\n\nsaturation\x18\x03 \x01(\x02\"\'\n\x05Sound\x12\x0f\n\x07noSound\x18\x01 \x01(\x08\x12\r\n\x05track\x18\x02 \x01(\t\"\x1b\n\tSoundList\x12\x0e\n\x06tracks\x18\x01 \x03(\t\"/\n\x06Status\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x12\x10\n\x08humidity\x18\x03 \x01(\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sound_light_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=21
  _globals['_MESSAGE']._serialized_end=103
  _globals['_REQUEST']._serialized_start=106
  _globals['_REQUEST']._serialized_end=236
  _globals['_RESPONSE']._serialized_start=238
  _globals['_RESPONSE']._serialized_end=364
  _globals['_GETSETTINGS']._serialized_start=366
  _globals['_GETSETTINGS']._serialized_end=452
  _globals['_SETTINGS']._serialized_start=455
  _globals['_SETTINGS']._serialized_end=631
  _globals['_COLOR']._serialized_start=633
  _globals['_COLOR']._serialized_end=690
  _globals['_SOUND']._serialized_start=692
  _globals['_SOUND']._serialized_end=731
  _globals['_SOUNDLIST']._serialized_start=733
  _globals['_SOUNDLIST']._serialized_end=760
  _globals['_STATUS']._serialized_start=762
  _globals['_STATUS']._serialized_end=809
# @@protoc_insertion_point(module_scope)
